name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Node
      uses: actions/setup-node@v2.1.5
    - name: Build
      run: yarn
    - name: Test
      with:
		    command-prefix: yarn dlx
      run: yarn test --ci
